site_name: ğŸš€ Msl Wiki
site_author: å§‹äºè¿è‡³

google_analytics: ['UA-36723568-3', 'mkdocs.org']

repo_url: https://MSL_wiki
repo_name: 'Msl GitHub'
copyright: "Copyright 2023 å§‹äºè¿è‡³"

docs_dir: 'docs'

theme:
  name: 'material'
